// AUTO-GENERATED by developerFrontEnd/scripts/build-demo-plan.js — do not hand-edit.
// Re-run `node developerFrontEnd/scripts/build-demo-plan.js` from the repo root
// to roll a fresh random set of 8 meals from backend/meals.json.
import type { ShoppingPlanResponse } from '@/services/api';

export const DEMO_MEAL_PLAN: ShoppingPlanResponse = {
  "meal_plan": [
    {
      "day": "Monday",
      "day_index": 0,
      "meal_type": "Breakfast",
      "name": "Cheesy Egg Quesadilla",
      "calories": 480,
      "cook_time": "10 minutes",
      "cook_time_minutes": 10,
      "cuisine": "American",
      "ingredients": [
        {
          "name": "Large eggs",
          "qty": 2,
          "unit": "whole",
          "price": 3.49
        },
        {
          "name": "Flour tortillas large",
          "qty": 2,
          "unit": "whole",
          "price": 1
        },
        {
          "name": "Shredded cheddar",
          "qty": 0.5,
          "unit": "cups",
          "price": 3.29
        },
        {
          "name": "Baby spinach",
          "qty": 1,
          "unit": "cups",
          "price": 2.62
        },
        {
          "name": "Red bell peppers",
          "qty": 0.25,
          "unit": "whole",
          "price": 1.46
        },
        {
          "name": "Vegetable oil",
          "qty": 1,
          "unit": "tsp"
        },
        {
          "name": "Salt",
          "qty": 0.25,
          "unit": "tsp"
        },
        {
          "name": "Black pepper",
          "qty": 0.25,
          "unit": "tsp"
        }
      ],
      "instructions": [
        "Dice the bell pepper; whisk eggs with salt and pepper.",
        "Scramble eggs in a lightly oiled skillet over medium heat until just set; stir in spinach until wilted.",
        "Lay one tortilla flat; scatter half the cheddar, the egg mixture, diced pepper, and remaining cheddar on one half.",
        "Fold the tortilla in half and cook in the skillet 2 minutes per side until golden.",
        "Slice into wedges and serve."
      ]
    },
    {
      "day": "Monday",
      "day_index": 0,
      "meal_type": "Lunch",
      "name": "Grilled Chicken Caesar Salad",
      "calories": 430,
      "cook_time": "20 minutes",
      "cook_time_minutes": 20,
      "cuisine": "American",
      "ingredients": [
        {
          "name": "Boneless skinless chicken breast",
          "qty": 6,
          "unit": "oz",
          "price": 6.49
        },
        {
          "name": "Romaine lettuce",
          "qty": 3,
          "unit": "cups",
          "price": 4.21
        },
        {
          "name": "Parmesan cheese",
          "qty": 2,
          "unit": "tbsp",
          "price": 4.49
        },
        {
          "name": "Lemons",
          "qty": 0.5,
          "unit": "whole",
          "price": 1.56
        },
        {
          "name": "Mayonnaise",
          "qty": 2,
          "unit": "tbsp",
          "price": 2.51
        },
        {
          "name": "Garlic bulb",
          "qty": 1,
          "unit": "cloves",
          "price": 0.72
        },
        {
          "name": "Worcestershire sauce",
          "qty": 0.5,
          "unit": "tsp",
          "price": 2.15
        },
        {
          "name": "Olive oil",
          "qty": 1,
          "unit": "tbsp"
        },
        {
          "name": "Salt",
          "qty": 0.5,
          "unit": "tsp"
        },
        {
          "name": "Black pepper",
          "qty": 0.25,
          "unit": "tsp"
        }
      ],
      "instructions": [
        "Season chicken with salt, pepper, and a drizzle of olive oil.",
        "Grill or pan-sear chicken over medium-high heat 6–7 minutes per side until cooked through; slice thin.",
        "Whisk together mayonnaise, lemon juice, minced garlic, Worcestershire sauce, salt, and pepper.",
        "Chop romaine and place in a large bowl.",
        "Drizzle dressing over lettuce and toss well.",
        "Top with sliced chicken and grated Parmesan."
      ]
    },
    {
      "day": "Monday",
      "day_index": 0,
      "meal_type": "Dinner",
      "name": "Baked Lemon Herb Chicken",
      "calories": 430,
      "cook_time": "35 minutes",
      "cook_time_minutes": 35,
      "cuisine": "American",
      "ingredients": [
        {
          "name": "Boneless skinless chicken breast",
          "qty": 6,
          "unit": "oz",
          "price": 6.49
        },
        {
          "name": "Brown rice",
          "qty": 0.5,
          "unit": "cups",
          "price": 2.55
        },
        {
          "name": "Asparagus",
          "qty": 6,
          "unit": "stalks",
          "price": 3.39
        },
        {
          "name": "Lemons",
          "qty": 0.5,
          "unit": "whole",
          "price": 1.56
        },
        {
          "name": "Garlic bulb",
          "qty": 3,
          "unit": "cloves",
          "price": 0.72
        },
        {
          "name": "Olive oil",
          "qty": 2,
          "unit": "tbsp"
        },
        {
          "name": "Rosemary dried",
          "qty": 0.5,
          "unit": "tsp",
          "price": 2.89
        },
        {
          "name": "Thyme dried",
          "qty": 0.5,
          "unit": "tsp",
          "price": 3.06
        },
        {
          "name": "Garlic powder",
          "qty": 0.25,
          "unit": "tsp"
        },
        {
          "name": "Salt",
          "qty": 0.75,
          "unit": "tsp"
        },
        {
          "name": "Black pepper",
          "qty": 0.25,
          "unit": "tsp"
        }
      ],
      "instructions": [
        "Preheat oven to 400°F. Cook brown rice per package directions.",
        "Whisk olive oil, lemon juice, minced garlic, rosemary, thyme, garlic powder, salt, and pepper.",
        "Coat chicken in the mixture; place in a baking dish. Toss asparagus in remaining marinade and arrange alongside.",
        "Bake 22–25 minutes until chicken reaches 165°F.",
        "Slice chicken and serve over brown rice with asparagus."
      ]
    },
    {
      "day": "Tuesday",
      "day_index": 1,
      "meal_type": "Breakfast",
      "name": "Banana Oat Pancakes",
      "calories": 400,
      "cook_time": "15 minutes",
      "cook_time_minutes": 15,
      "cuisine": "American",
      "ingredients": [
        {
          "name": "Bananas",
          "qty": 1,
          "unit": "whole",
          "price": 1.19
        },
        {
          "name": "Rolled oats",
          "qty": 0.5,
          "unit": "cups",
          "price": 5.15
        },
        {
          "name": "Large eggs",
          "qty": 2,
          "unit": "whole",
          "price": 3.49
        },
        {
          "name": "Honey",
          "qty": 1,
          "unit": "tbsp",
          "price": 2.54
        },
        {
          "name": "Cinnamon ground",
          "qty": 0.5,
          "unit": "tsp",
          "price": 2.07
        },
        {
          "name": "Vanilla extract",
          "qty": 0.25,
          "unit": "tsp"
        },
        {
          "name": "Butter unsalted",
          "qty": 1,
          "unit": "tsp",
          "price": 4.29
        },
        {
          "name": "Maple syrup",
          "qty": 1,
          "unit": "tbsp",
          "price": 3.69
        },
        {
          "name": "Blueberries",
          "qty": 0.25,
          "unit": "cups",
          "price": 2.66
        }
      ],
      "instructions": [
        "Mash the banana well in a bowl until smooth.",
        "Mix in eggs, rolled oats, honey, cinnamon, and vanilla until combined.",
        "Heat a nonstick skillet over medium heat and melt butter.",
        "Scoop 2 tbsp of batter per pancake; cook 2–3 minutes until bubbles form, then flip and cook 1 minute.",
        "Serve topped with blueberries and a drizzle of maple syrup."
      ]
    },
    {
      "day": "Tuesday",
      "day_index": 1,
      "meal_type": "Dinner",
      "name": "Classic Beef Stew",
      "calories": 580,
      "cook_time": "90 minutes",
      "cook_time_minutes": 90,
      "cuisine": "American",
      "ingredients": [
        {
          "name": "Beef stew meat",
          "qty": 6,
          "unit": "oz",
          "price": 4.93
        },
        {
          "name": "Russet potatoes",
          "qty": 1,
          "unit": "whole",
          "price": 2.39
        },
        {
          "name": "Carrots",
          "qty": 1,
          "unit": "whole",
          "price": 0.74
        },
        {
          "name": "Celery",
          "qty": 1,
          "unit": "stalks",
          "price": 4.64
        },
        {
          "name": "Yellow onions",
          "qty": 0.5,
          "unit": "whole",
          "price": 1.71
        },
        {
          "name": "Garlic bulb",
          "qty": 2,
          "unit": "cloves",
          "price": 0.72
        },
        {
          "name": "Canned beef broth",
          "qty": 2,
          "unit": "cups",
          "price": 3.05
        },
        {
          "name": "Canned diced tomatoes",
          "qty": 0.5,
          "unit": "cans",
          "price": 2.2
        },
        {
          "name": "Tomato paste",
          "qty": 1,
          "unit": "tbsp",
          "price": 2.16
        },
        {
          "name": "Cornstarch",
          "qty": 1,
          "unit": "tbsp",
          "price": 2.4
        },
        {
          "name": "Worcestershire sauce",
          "qty": 1,
          "unit": "tbsp",
          "price": 2.15
        },
        {
          "name": "Thyme dried",
          "qty": 0.5,
          "unit": "tsp",
          "price": 3.06
        },
        {
          "name": "Bay leaves",
          "qty": 1,
          "unit": "leaves",
          "price": 4.49
        },
        {
          "name": "Olive oil",
          "qty": 1,
          "unit": "tbsp"
        },
        {
          "name": "Salt",
          "qty": 0.75,
          "unit": "tsp"
        },
        {
          "name": "Black pepper",
          "qty": 0.5,
          "unit": "tsp"
        }
      ],
      "instructions": [
        "Cut beef into 1-inch cubes and season with salt and pepper.",
        "Heat olive oil in a large pot over medium-high heat; brown beef on all sides about 5 minutes; remove and set aside.",
        "Dice onion, mince garlic, chop carrots and celery, and cube the potato.",
        "In the same pot, sauté onion and celery 3 minutes; add garlic and cook 1 minute.",
        "Stir in tomato paste, then add broth, diced tomatoes, Worcestershire, thyme, and bay leaf.",
        "Return beef to the pot; bring to a boil, reduce heat, cover, and simmer 60 minutes until beef is tender.",
        "Add potatoes and carrots; cook 20 more minutes until vegetables are soft.",
        "Mix cornstarch with 2 tbsp cold water; stir into stew and cook 2 minutes until thickened. Remove bay leaf."
      ]
    },
    {
      "day": "Tuesday",
      "day_index": 1,
      "meal_type": "Dinner",
      "name": "Chicken Tikka Masala",
      "calories": 580,
      "cook_time": "35 minutes",
      "cook_time_minutes": 35,
      "cuisine": "American",
      "ingredients": [
        {
          "name": "Boneless skinless chicken breast",
          "qty": 6,
          "unit": "oz",
          "price": 6.49
        },
        {
          "name": "Jasmine rice",
          "qty": 0.5,
          "unit": "cups",
          "price": 3.1
        },
        {
          "name": "Canned crushed tomatoes",
          "qty": 1,
          "unit": "cans",
          "price": 2.95
        },
        {
          "name": "Heavy whipping cream",
          "qty": 0.25,
          "unit": "cups",
          "price": 2.53
        },
        {
          "name": "Yellow onions",
          "qty": 0.5,
          "unit": "whole",
          "price": 1.71
        },
        {
          "name": "Garlic bulb",
          "qty": 3,
          "unit": "cloves",
          "price": 0.72
        },
        {
          "name": "Fresh ginger root",
          "qty": 0.5,
          "unit": "tsp",
          "price": 2.87
        },
        {
          "name": "Garam masala",
          "qty": 1.5,
          "unit": "tsp",
          "price": 2.88
        },
        {
          "name": "Curry powder",
          "qty": 1,
          "unit": "tsp",
          "price": 2.76
        },
        {
          "name": "Cumin ground",
          "qty": 0.5,
          "unit": "tsp",
          "price": 2.32
        },
        {
          "name": "Turmeric ground",
          "qty": 0.25,
          "unit": "tsp",
          "price": 2.75
        },
        {
          "name": "Cayenne pepper",
          "qty": 0.25,
          "unit": "tsp",
          "price": 2.4
        },
        {
          "name": "Olive oil",
          "qty": 1,
          "unit": "tbsp"
        },
        {
          "name": "Salt",
          "qty": 0.5,
          "unit": "tsp"
        }
      ],
      "instructions": [
        "Cook jasmine rice per package directions.",
        "Cut chicken into cubes; season with half the garam masala, salt, and cayenne.",
        "Cook chicken in olive oil over medium-high heat 4 minutes per side; remove.",
        "Sauté diced onion 4 minutes in the same pan; add minced garlic and grated ginger; cook 1 minute.",
        "Stir in remaining garam masala, curry powder, cumin, and turmeric; cook 1 minute.",
        "Add crushed tomatoes; simmer 10 minutes. Stir in cream; return chicken; simmer 5 more minutes.",
        "Serve over jasmine rice."
      ]
    },
    {
      "day": "Wednesday",
      "day_index": 2,
      "meal_type": "Breakfast",
      "name": "Banana Smoothie Bowl",
      "calories": 360,
      "cook_time": "5 minutes",
      "cook_time_minutes": 5,
      "cuisine": "American",
      "ingredients": [
        {
          "name": "Bananas",
          "qty": 1.5,
          "unit": "whole",
          "price": 1.19
        },
        {
          "name": "Blueberries",
          "qty": 0.5,
          "unit": "cups",
          "price": 2.66
        },
        {
          "name": "Strawberries",
          "qty": 0.5,
          "unit": "cups",
          "price": 5.29
        },
        {
          "name": "Raspberries",
          "qty": 0.25,
          "unit": "cups",
          "price": 4.82
        },
        {
          "name": "Rolled oats",
          "qty": 0.25,
          "unit": "cups",
          "price": 5.15
        },
        {
          "name": "Honey",
          "qty": 1,
          "unit": "tbsp",
          "price": 2.54
        },
        {
          "name": "Cinnamon ground",
          "qty": 0.25,
          "unit": "tsp",
          "price": 2.07
        }
      ],
      "instructions": [
        "Slice bananas (frozen bananas work best for a thicker base); mash 1 banana thoroughly with a fork until smooth and creamy.",
        "Spoon mashed banana into a bowl as the base.",
        "Hull and halve the strawberries; slice the remaining half banana.",
        "Arrange blueberries, strawberries, raspberries, and banana slices on top.",
        "Sprinkle with rolled oats, drizzle with honey, and dust with cinnamon."
      ]
    },
    {
      "day": "Wednesday",
      "day_index": 2,
      "meal_type": "Dinner",
      "name": "Turkey Meatballs in Marinara",
      "calories": 540,
      "cook_time": "35 minutes",
      "cook_time_minutes": 35,
      "cuisine": "Italian",
      "ingredients": [
        {
          "name": "Ground turkey",
          "qty": 5,
          "unit": "oz",
          "price": 5.49
        },
        {
          "name": "Spaghetti pasta",
          "qty": 3,
          "unit": "oz",
          "price": 4.08
        },
        {
          "name": "Marinara pasta sauce jar",
          "qty": 1,
          "unit": "cups",
          "price": 3.81
        },
        {
          "name": "Plain bread crumbs",
          "qty": 3,
          "unit": "tbsp",
          "price": 3.14
        },
        {
          "name": "Parmesan cheese",
          "qty": 3,
          "unit": "tbsp",
          "price": 4.49
        },
        {
          "name": "Large eggs",
          "qty": 1,
          "unit": "whole",
          "price": 3.49
        },
        {
          "name": "Garlic bulb",
          "qty": 2,
          "unit": "cloves",
          "price": 0.72
        },
        {
          "name": "Italian seasoning",
          "qty": 1,
          "unit": "tsp",
          "price": 2.63
        },
        {
          "name": "Olive oil",
          "qty": 1,
          "unit": "tbsp"
        },
        {
          "name": "Salt",
          "qty": 0.5,
          "unit": "tsp"
        },
        {
          "name": "Black pepper",
          "qty": 0.25,
          "unit": "tsp"
        }
      ],
      "instructions": [
        "Mix ground turkey, bread crumbs, egg, minced garlic, Italian seasoning, salt, and pepper; form into walnut-sized balls.",
        "Brown meatballs in olive oil over medium heat 3 minutes per side.",
        "Add marinara sauce; bring to a simmer, cover, and cook 15 minutes until cooked through.",
        "Cook spaghetti in salted boiling water; drain.",
        "Serve meatballs and sauce over spaghetti; finish with Parmesan."
      ]
    }
  ],
  "route": [
    "Meijer",
    "Aldi",
    "Target"
  ],
  "total_cost": 197.98,
  "cheapest_single_store_cost": 233.62,
  "cheapest_single_store_name": "Target",
  "total_time_minutes": 135,
  "user_location": {
    "lat": 39.8283,
    "lng": -86.148
  },
  "at_home_ingredients": [
    {
      "name": "Olive oil",
      "qty": 1,
      "unit": "tbsp"
    },
    {
      "name": "Salt",
      "qty": 0.75,
      "unit": "tsp"
    },
    {
      "name": "Black pepper",
      "qty": 0.5,
      "unit": "tsp"
    },
    {
      "name": "Vegetable oil",
      "qty": 1,
      "unit": "tsp"
    },
    {
      "name": "Vanilla extract",
      "qty": 0.25,
      "unit": "tsp"
    },
    {
      "name": "Garlic powder",
      "qty": 0.25,
      "unit": "tsp"
    }
  ],
  "warnings": [
    "Dietary restriction \"Vegetarian\" was PARTLY ENFORCED — this demo plan mixes vegetarian and non-vegetarian recipes for variety.",
    "Max cook time preference of 30 minutes was relaxed for 1 recipe (Classic Beef Stew, 90 min) to preserve meal variety."
  ],
  "budget": 150,
  "over_budget": true,
  "shopping_list": [
    {
      "store": "Meijer",
      "address": "5350 E 86th St, Indianapolis, IN 46250",
      "coordinates": {
        "lat": 39.8968,
        "lng": -86.1133
      },
      "items": [
        {
          "name": "Large eggs",
          "qty": 3,
          "price": 10.47,
          "product_name": "Large Eggs",
          "size_str": "6 ct",
          "units_to_buy": 3
        },
        {
          "name": "Boneless skinless chicken breast",
          "qty": 3,
          "price": 19.47,
          "product_name": "Boneless Skinless Chicken Breast",
          "size_str": "1 unit",
          "units_to_buy": 3,
          "original_price": 19.47,
          "coupon": {
            "type": "digital",
            "label": "$2.50 off Boneless Skinless Chicken Breast",
            "savings": 2.5,
            "image_url": "https://example.com/coupons/demo.png",
            "valid_to": "2026-08-31"
          }
        },
        {
          "name": "Parmesan cheese",
          "qty": 2,
          "price": 8.98,
          "product_name": "Parmesan Cheese",
          "size_str": "2.5 oz",
          "units_to_buy": 2
        },
        {
          "name": "Butter unsalted",
          "qty": 1,
          "price": 4.29,
          "product_name": "Butter Unsalted",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Beef stew meat",
          "qty": 1,
          "price": 4.93,
          "product_name": "Beef Stew Meat",
          "size_str": "1 unit",
          "units_to_buy": 1
        },
        {
          "name": "Canned beef broth",
          "qty": 1,
          "price": 3.05,
          "product_name": "Canned Beef Broth",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Heavy whipping cream",
          "qty": 1,
          "price": 2.53,
          "product_name": "Heavy Whipping Cream",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Ground turkey",
          "qty": 1,
          "price": 5.49,
          "product_name": "Ground Turkey",
          "size_str": "1 unit",
          "units_to_buy": 1
        }
      ]
    },
    {
      "store": "Aldi",
      "address": "3902 N Illinois St, Indianapolis, IN 46208",
      "coordinates": {
        "lat": 39.8109,
        "lng": -86.1614
      },
      "items": [
        {
          "name": "Baby spinach",
          "qty": 1,
          "price": 2.62,
          "product_name": "Baby Spinach",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Red bell peppers",
          "qty": 1,
          "price": 1.46,
          "product_name": "Red Bell Peppers",
          "size_str": "6 ct",
          "units_to_buy": 1
        },
        {
          "name": "Romaine lettuce",
          "qty": 1,
          "price": 4.21,
          "product_name": "Romaine Lettuce",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Lemons",
          "qty": 2,
          "price": 3.12,
          "product_name": "Lemons",
          "size_str": "6 ct",
          "units_to_buy": 2
        },
        {
          "name": "Garlic bulb",
          "qty": 3,
          "price": 2.16,
          "product_name": "Garlic Bulb",
          "size_str": "3 oz",
          "units_to_buy": 3
        },
        {
          "name": "Bananas",
          "qty": 2,
          "price": 2.38,
          "product_name": "Bananas",
          "size_str": "6 ct",
          "units_to_buy": 2
        },
        {
          "name": "Blueberries",
          "qty": 2,
          "price": 5.32,
          "product_name": "Blueberries",
          "size_str": "32 oz",
          "units_to_buy": 2
        },
        {
          "name": "Russet potatoes",
          "qty": 1,
          "price": 2.39,
          "product_name": "Russet Potatoes",
          "size_str": "6 ct",
          "units_to_buy": 1
        },
        {
          "name": "Carrots",
          "qty": 1,
          "price": 0.74,
          "product_name": "Carrots",
          "size_str": "6 ct",
          "units_to_buy": 1
        },
        {
          "name": "Yellow onions",
          "qty": 2,
          "price": 3.42,
          "product_name": "Yellow Onions",
          "size_str": "6 ct",
          "units_to_buy": 2
        },
        {
          "name": "Canned diced tomatoes",
          "qty": 1,
          "price": 2.2,
          "product_name": "Canned Diced Tomatoes",
          "size_str": "1 unit",
          "units_to_buy": 1
        },
        {
          "name": "Tomato paste",
          "qty": 1,
          "price": 2.16,
          "product_name": "Tomato Paste",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Canned crushed tomatoes",
          "qty": 1,
          "price": 2.95,
          "product_name": "Canned Crushed Tomatoes",
          "size_str": "1 unit",
          "units_to_buy": 1
        },
        {
          "name": "Cayenne pepper",
          "qty": 1,
          "price": 2.4,
          "product_name": "Cayenne Pepper",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Strawberries",
          "qty": 1,
          "price": 5.29,
          "product_name": "Strawberries",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Raspberries",
          "qty": 1,
          "price": 4.82,
          "product_name": "Raspberries",
          "size_str": "32 oz",
          "units_to_buy": 1
        }
      ]
    },
    {
      "store": "Target",
      "address": "8210 Craig St, Indianapolis, IN 46250",
      "coordinates": {
        "lat": 39.8712,
        "lng": -86.1329
      },
      "items": [
        {
          "name": "Flour tortillas large",
          "qty": 1,
          "price": 1,
          "product_name": "Flour Tortillas Large",
          "size_str": "6 ct",
          "units_to_buy": 1
        },
        {
          "name": "Shredded cheddar",
          "qty": 1,
          "price": 3.29,
          "product_name": "Shredded Cheddar",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Mayonnaise",
          "qty": 1,
          "price": 2.51,
          "product_name": "Mayonnaise",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Worcestershire sauce",
          "qty": 2,
          "price": 4.3,
          "product_name": "Worcestershire Sauce",
          "size_str": "2.5 oz",
          "units_to_buy": 2
        },
        {
          "name": "Brown rice",
          "qty": 1,
          "price": 2.55,
          "product_name": "Brown Rice",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Asparagus",
          "qty": 1,
          "price": 3.39,
          "product_name": "Asparagus",
          "size_str": "1 unit",
          "units_to_buy": 1
        },
        {
          "name": "Rosemary dried",
          "qty": 1,
          "price": 2.89,
          "product_name": "Rosemary Dried",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Thyme dried",
          "qty": 2,
          "price": 6.12,
          "product_name": "Thyme Dried",
          "size_str": "2.5 oz",
          "units_to_buy": 2
        },
        {
          "name": "Rolled oats",
          "qty": 2,
          "price": 10.3,
          "product_name": "Rolled Oats",
          "size_str": "32 oz",
          "units_to_buy": 2
        },
        {
          "name": "Honey",
          "qty": 2,
          "price": 5.08,
          "product_name": "Honey",
          "size_str": "2.5 oz",
          "units_to_buy": 2
        },
        {
          "name": "Cinnamon ground",
          "qty": 2,
          "price": 4.14,
          "product_name": "Cinnamon Ground",
          "size_str": "2.5 oz",
          "units_to_buy": 2
        },
        {
          "name": "Maple syrup",
          "qty": 1,
          "price": 3.69,
          "product_name": "Maple Syrup",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Celery",
          "qty": 1,
          "price": 4.64,
          "product_name": "Celery",
          "size_str": "1 unit",
          "units_to_buy": 1
        },
        {
          "name": "Cornstarch",
          "qty": 1,
          "price": 2.4,
          "product_name": "Cornstarch",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Bay leaves",
          "qty": 1,
          "price": 4.49,
          "product_name": "Bay Leaves",
          "size_str": "1 unit",
          "units_to_buy": 1
        },
        {
          "name": "Jasmine rice",
          "qty": 1,
          "price": 3.1,
          "product_name": "Jasmine Rice",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Fresh ginger root",
          "qty": 1,
          "price": 2.87,
          "product_name": "Fresh Ginger Root",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Garam masala",
          "qty": 1,
          "price": 2.88,
          "product_name": "Garam Masala",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Curry powder",
          "qty": 1,
          "price": 2.76,
          "product_name": "Curry Powder",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Cumin ground",
          "qty": 1,
          "price": 2.32,
          "product_name": "Cumin Ground",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Turmeric ground",
          "qty": 1,
          "price": 2.75,
          "product_name": "Turmeric Ground",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Spaghetti pasta",
          "qty": 1,
          "price": 4.08,
          "product_name": "Spaghetti Pasta",
          "size_str": "1 unit",
          "units_to_buy": 1
        },
        {
          "name": "Marinara pasta sauce jar",
          "qty": 1,
          "price": 3.81,
          "product_name": "Marinara Pasta Sauce Jar",
          "size_str": "32 oz",
          "units_to_buy": 1
        },
        {
          "name": "Plain bread crumbs",
          "qty": 1,
          "price": 3.14,
          "product_name": "Plain Bread Crumbs",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        },
        {
          "name": "Italian seasoning",
          "qty": 1,
          "price": 2.63,
          "product_name": "Italian Seasoning",
          "size_str": "2.5 oz",
          "units_to_buy": 1
        }
      ],
      "estimated": true,
      "pricing_note": "Prices at this Target are typical in-store estimates; exact totals may vary slightly by location."
    }
  ]
};
