// AUTO-GENERATED by developerFrontEnd/scripts/build-demo-plan.js — do not hand-edit.
// Fixed pool of fabricated addresses used by the demo /location autocomplete.
// ADDRESS_POOL[0] is the "home" address baked into demoMealPlan.ts's user_location.

export const DEMO_ADDRESS_POOL: string[] = [
  "4821 N Pennsylvania St, Indianapolis, IN 46205",
  "5350 E 86th St, Indianapolis, IN 46250",
  "3902 N Illinois St, Indianapolis, IN 46208",
  "8210 Craig St, Indianapolis, IN 46250",
  "620 N College Ave, Indianapolis, IN 46202",
  "7255 N Keystone Ave, Indianapolis, IN 46240"
];
