# Maps each of the 199 approved meal-cache ingredient names to the best
# 1-2 word Kroger search term. Keeps searches short so the Kroger API
# returns relevant results (long exact names often fail or return noise).

KROGER_SEARCH_TERMS: dict[str, str] = {

    # ── Produce — Vegetables ──────────────────────────────────────────
    "Yellow onions":            "yellow onions",
    "Red onions":               "red onions",
    "Green onions":             "green onions",
    "Garlic bulb":              "fresh garlic",
    "Fresh ginger root":        "fresh ginger",
    "Baby spinach":             "baby spinach",
    "Romaine lettuce":          "romaine lettuce",
    "Iceberg lettuce":          "iceberg lettuce",
    "Kale":                     "kale",
    "Broccoli":                 "broccoli",
    "Cauliflower":              "cauliflower",
    "Brussels sprouts":         "brussels sprouts",
    "Green beans":              "green beans",
    "Asparagus":                "asparagus",
    "Zucchini":                 "zucchini",
    "Yellow squash":            "yellow squash",
    "Red bell peppers":         "red bell pepper",
    "Green bell peppers":       "green bell pepper",
    "Jalapenos":                "jalapeno",
    "Carrots":                  "carrots",
    "Celery":                   "celery",
    "Cucumber":                 "cucumber",
    "Vine tomatoes":            "vine tomatoes",
    "Cherry tomatoes":          "cherry tomatoes",
    "Roma tomatoes":            "roma tomatoes",
    "Russet potatoes":          "russet potatoes",
    "Sweet potatoes":           "sweet potatoes",
    "Red potatoes":             "red potatoes",
    "Corn on the cob":          "corn cob",
    "White mushrooms":          "white mushrooms",
    "Baby bella mushrooms":     "baby bella mushrooms",
    "Cabbage green":            "green cabbage",
    "Red cabbage":              "red cabbage",
    "Bok choy":                 "bok choy",
    "Snap peas":                "snap peas",
    "Baby carrots":             "baby carrots",
    "Radishes":                 "radishes",
    "Beets":                    "beets",
    "Butternut squash":         "butternut squash",
    "Spaghetti squash":         "spaghetti squash",

    # ── Produce — Fruits ─────────────────────────────────────────────
    "Bananas":                  "bananas",
    "Gala apples":              "gala apples",
    "Lemons":                   "lemons",
    "Limes":                    "limes",
    "Navel oranges":            "navel oranges",
    "Strawberries":             "strawberries",
    "Blueberries":              "blueberries",
    "Red seedless grapes":      "red grapes",
    "Mangos":                   "mango",
    "Fresh pineapple":          "pineapple",
    "Peaches":                  "peaches",
    "Raspberries":              "raspberries",
    "Avocados":                 "avocado",
    "Watermelon":               "watermelon",
    "Blackberries":             "blackberries",

    # ── Meat & Seafood ────────────────────────────────────────────────
    "Boneless skinless chicken breast":  "boneless chicken breast",
    "Boneless skinless chicken thighs":  "boneless chicken thighs",
    "Ground beef 80/20":                 "ground beef",
    "Ground turkey":                     "ground turkey",
    "Boneless pork chops":               "pork chops",
    "Pork tenderloin":                   "pork tenderloin",
    "Bacon":                             "bacon",
    "Italian sausage links":             "italian sausage",
    "Breakfast sausage links":           "breakfast sausage",
    "Beef stew meat":                    "beef stew meat",
    "Sirloin steak":                     "sirloin steak",
    "Salmon fillet":                     "salmon",
    "Tilapia fillet":                    "tilapia",
    "Frozen shrimp medium":              "shrimp",
    "Canned tuna in water":              "canned tuna",
    "Hot dogs":                          "hot dogs",
    "Deli turkey breast":                "deli turkey",
    "Deli ham":                          "deli ham",
    "Pepperoni":                         "pepperoni",
    "Ground pork":                       "ground pork",
    "Beef short ribs":                   "beef short ribs",
    "Ground lamb":                       "ground lamb",
    "Imitation crab meat":               "imitation crab",
    "Rotisserie chicken":                "rotisserie chicken",
    "Chicken wings":                     "chicken wings",

    # ── Dairy & Eggs ─────────────────────────────────────────────────
    "Large eggs":               "eggs",
    "Whole milk gallon":        "whole milk",
    "2% milk gallon":           "2% milk",
    "Butter unsalted":          "unsalted butter",
    "Salted butter":            "salted butter",
    "Heavy whipping cream":     "heavy cream",
    "Sour cream":               "sour cream",
    "Plain Greek yogurt":       "greek yogurt",
    "Cream cheese":             "cream cheese",
    "Shredded mozzarella":      "shredded mozzarella",
    "Shredded cheddar":         "shredded cheddar",
    "Parmesan cheese":          "parmesan cheese",
    "Monterey jack cheese":     "monterey jack",
    "Cottage cheese":           "cottage cheese",
    "Half and half":            "half and half",

    # ── Bread & Bakery ────────────────────────────────────────────────
    "White sandwich bread":     "white sandwich bread",
    "Whole wheat bread":        "whole wheat bread",
    "Flour tortillas large":    "flour tortillas",
    "Corn tortillas":           "corn tortillas",
    "Hamburger buns":           "buns",

    # ── Grains & Pasta ────────────────────────────────────────────────
    "White rice long grain":    "long grain white rice",
    "Brown rice":               "brown rice",
    "Jasmine rice":             "jasmine rice",
    "Spaghetti pasta":          "spaghetti",
    "Penne pasta":              "penne rigate",
    "Elbow macaroni":           "elbow macaroni",
    "Egg noodles":              "egg noodles",
    "Lasagna noodles":          "lasagna noodles",
    "Rolled oats":              "old fashioned oats",
    "Panko bread crumbs":       "panko",
    "Plain bread crumbs":       "bread crumbs",
    "All purpose flour":        "all purpose flour",
    "Cornmeal":                 "cornmeal",
    "Quinoa":                   "quinoa",
    "Ramen noodles":            "ramen noodles",
    "Orzo pasta":               "orzo",

    # ── Canned & Jarred Goods ─────────────────────────────────────────
    "Canned diced tomatoes":             "diced tomatoes",
    "Canned crushed tomatoes":           "crushed tomatoes",
    "Tomato paste":                      "tomato paste",
    "Tomato sauce":                      "tomato sauce",
    "Canned black beans":                "canned black beans",
    "Canned kidney beans":               "kidney beans",
    "Canned chickpeas":                  "chickpeas",
    "Canned corn":                       "canned corn",
    "Canned green beans":                "canned green beans",
    "Canned coconut milk":               "coconut milk",
    "Canned chicken broth":              "chicken broth",
    "Canned beef broth":                 "beef broth",
    "Canned diced green chiles":         "diced green chiles",
    "Refried beans":                     "refried beans",
    "Canned pinto beans":                "pinto beans",
    "Salsa jar":                         "salsa",
    "Marinara pasta sauce jar":          "marinara sauce",
    "Diced tomatoes with green chiles":  "rotel",
    "Canned lentils":                    "canned lentils",
    "Artichoke hearts canned":           "artichoke hearts",
    "Sun dried tomatoes jar":            "sundried tomatoes",
    "Roasted red peppers jar":           "roasted red peppers",
    "Canned pumpkin":                    "canned pumpkin",
    "Chicken noodle soup can":           "chicken noodle soup",
    "Tomato soup can":                   "tomato soup",

    # ── Oils, Sauces & Condiments ─────────────────────────────────────
    "Olive oil":                "olive oil",
    "Vegetable oil":            "pure vegetable oil",
    "Sesame oil":               "sesame oil",
    "Soy sauce":                "soy sauce",
    "Worcestershire sauce":     "worcestershire sauce",
    "Hot sauce":                "hot sauce",
    "Ketchup":                  "ketchup",
    "Yellow mustard":           "french yellow mustard",
    "Dijon mustard":            "dijon mustard",
    "Mayonnaise":               "mayonnaise",
    "Apple cider vinegar":      "apple cider vinegar",
    "White vinegar":            "white vinegar",
    "Balsamic vinegar":         "balsamic vinegar",
    "Honey":                    "honey",
    "Maple syrup":              "maple syrup",
    "Fish sauce":               "fish sauce",
    "Oyster sauce":             "oyster sauce",
    "Hoisin sauce":             "hoisin",
    "Sriracha":                 "sriracha",
    "Ranch dressing":           "ranch dressing",

    # ── Baking & Dry Goods ────────────────────────────────────────────
    "Granulated sugar":         "granulated sugar",
    "Brown sugar":              "brown sugar",
    "Powdered sugar":           "powdered sugar",
    "Baking soda":              "baking soda",
    "Baking powder":            "baking powder",
    "Salt":                     "salt",
    "Black pepper":             "black pepper",
    "Chicken bouillon cubes":   "chicken bouillon",
    "Beef bouillon cubes":      "beef bouillon",
    "Cornstarch":               "cornstarch",
    "Vanilla extract":          "vanilla extract",
    "Cocoa powder":             "cocoa powder",
    "Chocolate chips":          "chocolate chips",
    "Peanut butter":            "peanut butter",
    "Almond butter":            "almond butter",
    "Strawberry jam":           "strawberry jam",
    "Active dry yeast":         "active dry yeast",
    "Red lentils dried":        "lentils",             # "red lentils" returns lentil pasta

    # ── Spices & Seasonings ───────────────────────────────────────────
    "Garlic powder":            "garlic powder",
    "Onion powder":             "onion powder",
    "Cumin ground":             "cumin",
    "Chili powder":             "chili powder",
    "Smoked paprika":           "smoked paprika",
    "Cayenne pepper":           "cayenne pepper",
    "Italian seasoning":        "italian herb seasoning",
    "Oregano dried":            "oregano",
    "Thyme dried":              "thyme",
    "Rosemary dried":           "rosemary",
    "Bay leaves":               "bay leaves",
    "Cinnamon ground":          "cinnamon",
    "Curry powder":             "curry powder",
    "Turmeric ground":          "turmeric",
    "Red pepper flakes":        "red pepper flakes",
    "Garam masala":             "garam masala",        # may return wrong item if store doesn't stock it; acceptable fallback
    "Taco seasoning":           "taco seasoning",
    "Everything bagel seasoning": "everything bagel seasoning",
    "Old bay seasoning":        "old bay",
    "Coriander ground":         "coriander",
}


# Ordered fallback terms to try when the primary term returns no result or no price.
# Each list has 5 terms, from most-specific to most-generic.
KROGER_FALLBACKS: dict[str, list[str]] = {

    # ── Produce — Vegetables ──────────────────────────────────────────
    "Yellow onions":           ["onion", "yellow onion", "onions", "sweet onion", "white onion"],
    "Red onions":              ["onion", "red onion", "purple onion", "onions", "shallots"],
    "Green onions":            ["scallions", "green onion", "spring onions", "chives", "onion"],
    "Garlic bulb":             ["garlic cloves", "garlic head", "fresh garlic cloves", "whole garlic", "garlic"],
    "Fresh ginger root":       ["ginger", "ginger root", "fresh ginger", "ground ginger", "spice"],
    "Baby spinach":            ["spinach", "fresh spinach", "spinach leaves", "baby greens", "greens"],
    "Romaine lettuce":         ["romaine", "lettuce", "romaine hearts", "salad greens", "green lettuce"],
    "Iceberg lettuce":         ["iceberg", "lettuce", "head lettuce", "salad greens", "lettuce head"],
    "Kale":                    ["kale leaves", "curly kale", "fresh kale", "leafy greens", "greens"],
    "Broccoli":                ["broccoli florets", "fresh broccoli", "broccoli crown", "cruciferous", "vegetables"],
    "Cauliflower":             ["cauliflower head", "fresh cauliflower", "cauliflower florets", "broccoli", "vegetables"],
    "Brussels sprouts":        ["brussels", "brussel sprouts", "sprouts", "mini cabbages", "vegetables"],
    "Green beans":             ["string beans", "snap beans", "fresh green beans", "haricot verts", "beans"],
    "Asparagus":               ["asparagus spears", "fresh asparagus", "green asparagus", "asparagus bunch", "vegetables"],
    "Zucchini":                ["zucchini squash", "summer squash", "courgette", "green squash", "squash"],
    "Yellow squash":           ["summer squash", "yellow zucchini", "squash", "crookneck squash", "vegetables"],
    "Red bell peppers":        ["bell pepper", "red pepper", "sweet pepper", "peppers", "pepper"],
    "Green bell peppers":      ["bell pepper", "green pepper", "sweet pepper", "peppers", "pepper"],
    "Jalapenos":               ["jalapeno pepper", "hot pepper", "chili pepper", "fresh jalapeno", "peppers"],
    "Carrots":                 ["carrot", "fresh carrots", "whole carrots", "baby carrots", "root vegetables"],
    "Celery":                  ["celery stalks", "celery bunch", "fresh celery", "celery ribs", "vegetables"],
    "Cucumber":                ["cucumbers", "english cucumber", "fresh cucumber", "mini cucumber", "slicing cucumber"],
    "Vine tomatoes":           ["tomatoes", "vine ripened tomatoes", "fresh tomatoes", "tomato", "beefsteak tomato"],
    "Cherry tomatoes":         ["grape tomatoes", "tomatoes", "mini tomatoes", "fresh tomatoes", "tomato"],
    "Roma tomatoes":           ["plum tomatoes", "tomatoes", "fresh tomatoes", "italian tomatoes", "tomato"],
    "Russet potatoes":         ["potatoes", "baking potato", "idaho potato", "potato", "russet"],
    "Sweet potatoes":          ["yams", "sweet potato", "jewel yam", "orange potato", "potato"],
    "Red potatoes":            ["potatoes", "red skin potato", "new potatoes", "baby potatoes", "potato"],
    "Corn on the cob":         ["corn", "fresh corn", "sweet corn", "corn cobs", "ears of corn"],
    "White mushrooms":         ["mushrooms", "button mushrooms", "sliced mushrooms", "cremini", "fungi"],
    "Baby bella mushrooms":    ["cremini mushrooms", "mushrooms", "portobello mushrooms", "baby portobello", "fungi"],
    "Cabbage green":           ["cabbage", "green cabbage head", "head of cabbage", "coleslaw mix", "vegetables"],
    "Red cabbage":             ["cabbage", "purple cabbage", "red cabbage head", "coleslaw mix", "vegetables"],
    "Bok choy":                ["bok choy baby", "pak choy", "chinese cabbage", "asian greens", "cabbage"],
    "Snap peas":               ["sugar snap peas", "snap peas fresh", "snow peas", "fresh snap peas", "pea pods"],
    "Baby carrots":            ["carrots", "mini carrots", "peeled carrots", "carrot sticks", "carrots bag"],
    "Radishes":                ["radish", "fresh radishes", "daikon", "red radishes", "vegetables"],
    "Beets":                   ["beet", "fresh beets", "red beets", "golden beets", "root vegetables"],
    "Butternut squash":        ["squash", "winter squash", "butternut", "acorn squash", "vegetables"],
    "Spaghetti squash":        ["squash", "winter squash", "spaghetti squash whole", "vegetable squash", "vegetables"],

    # ── Produce — Fruits ─────────────────────────────────────────────
    "Bananas":                 ["banana", "yellow bananas", "ripe bananas", "banana bunch", "fruit"],
    "Gala apples":             ["apples", "apple", "fuji apple", "honeycrisp apple", "red apple"],
    "Lemons":                  ["fresh lemon", "lemon fruit", "yellow lemon", "lemon bag", "citrus lemon"],
    "Limes":                   ["fresh lime", "lime fruit", "green lime", "lime bag", "key lime"],
    "Navel oranges":           ["oranges", "orange", "citrus", "mandarin", "clementine"],
    "Strawberries":            ["strawberry", "fresh strawberries", "berries", "strawberry pint", "fruit"],
    "Blueberries":             ["blueberry", "fresh blueberries", "berries", "wild blueberries", "fruit"],
    "Red seedless grapes":     ["grapes", "red grapes", "seedless grapes", "grape bunch", "fruit"],
    "Mangos":                  ["mango", "fresh mango", "ataulfo mango", "tropical fruit", "fruit"],
    "Fresh pineapple":         ["pineapple", "fresh pineapple whole", "pineapple chunks", "tropical fruit", "fruit"],
    "Peaches":                 ["peach", "fresh peaches", "nectarine", "stone fruit", "fruit"],
    "Raspberries":             ["raspberry", "fresh raspberries", "berries", "red berries", "fruit"],
    "Avocados":                ["hass avocado", "avocado", "fresh avocado", "ripe avocado", "fruit"],
    "Watermelon":              ["watermelon whole", "seedless watermelon", "mini watermelon", "melon", "fruit"],
    "Blackberries":            ["blackberry", "fresh blackberries", "berries", "marionberry", "fruit"],

    # ── Meat & Seafood ────────────────────────────────────────────────
    "Boneless skinless chicken breast":  ["chicken breast", "chicken", "boneless chicken", "skinless chicken", "poultry"],
    "Boneless skinless chicken thighs":  ["chicken thigh", "boneless thighs", "chicken", "dark meat chicken", "poultry"],
    "Ground beef 80/20":                 ["ground beef", "hamburger meat", "beef", "lean ground beef", "chuck"],
    "Ground turkey":                     ["turkey", "lean turkey", "ground turkey breast", "turkey meat", "poultry"],
    "Boneless pork chops":               ["pork chops", "pork", "center cut pork", "loin chops", "boneless pork"],
    "Pork tenderloin":                   ["pork loin", "pork", "tenderloin", "pork roast", "pork filet"],
    "Bacon":                             ["bacon strips", "sliced bacon", "pork bacon", "turkey bacon", "breakfast meat"],
    "Italian sausage links":             ["sausage", "pork sausage", "italian sausage", "sausage links", "brats"],
    "Breakfast sausage links":           ["sausage links", "sausage", "pork sausage", "breakfast meat", "morning sausage"],
    "Beef stew meat":                    ["stew beef", "beef cubes", "beef chuck", "braising beef", "beef"],
    "Sirloin steak":                     ["steak", "beef steak", "top sirloin", "sirloin", "beef"],
    "Salmon fillet":                     ["fresh salmon", "atlantic salmon", "salmon fillet", "fish fillet", "seafood"],
    "Tilapia fillet":                    ["tilapia fish", "tilapia fillets", "fish", "white fish", "seafood"],
    "Frozen shrimp medium":              ["frozen shrimp", "shrimp", "peeled shrimp", "raw shrimp", "seafood"],
    "Canned tuna in water":              ["tuna", "albacore tuna", "chunk tuna", "canned fish", "seafood"],
    "Hot dogs":                          ["frankfurters", "wieners", "beef hot dogs", "franks", "sausage"],
    "Deli turkey breast":                ["turkey breast", "sliced turkey", "lunch meat turkey", "deli meat", "cold cuts"],
    "Deli ham":                          ["sliced ham", "lunch meat ham", "ham", "deli meat", "cold cuts"],
    "Pepperoni":                         ["pepperoni slices", "pizza pepperoni", "turkey pepperoni", "salami", "deli meat"],
    "Ground pork":                       ["pork", "ground pork sausage", "pork mince", "bulk pork sausage", "pork meat"],
    "Beef short ribs":                   ["short ribs", "beef ribs", "ribs", "braising beef", "beef"],
    "Ground lamb":                       ["lamb", "lamb meat", "ground lamb patties", "lamb mince", "lamb chops"],
    "Imitation crab meat":               ["crab", "imitation crab", "surimi", "seafood sticks", "krab"],
    "Rotisserie chicken":                ["cooked chicken", "whole chicken", "deli chicken", "ready chicken", "chicken"],
    "Chicken wings":                     ["wings", "chicken wing", "buffalo wings", "party wings", "wing sections"],

    # ── Dairy & Eggs ─────────────────────────────────────────────────
    "Large eggs":              ["dozen eggs", "eggs large", "white eggs", "brown eggs", "grade a eggs"],
    "Whole milk gallon":       ["milk gallon", "milk", "full fat milk", "vitamin d milk", "dairy milk"],
    "2% milk gallon":          ["reduced fat milk", "milk gallon", "low fat milk", "milk", "dairy"],
    "Butter unsalted":         ["butter", "sweet cream butter", "unsalted butter sticks", "land o lakes", "margarine"],
    "Salted butter":           ["butter", "salted butter sticks", "sweet cream salted butter", "butter sticks", "margarine"],
    "Heavy whipping cream":    ["whipping cream", "cream", "heavy cream", "double cream", "dairy cream"],
    "Sour cream":              ["sour cream full fat", "daisy sour cream", "cream", "creme fraiche", "dairy"],
    "Plain Greek yogurt":      ["greek yogurt plain", "yogurt", "nonfat greek yogurt", "plain yogurt", "dairy"],
    "Cream cheese":            ["cream cheese block", "philadelphia cream cheese", "neufchatel", "soft cheese", "dairy"],
    "Shredded mozzarella":     ["mozzarella cheese", "mozzarella", "pizza cheese", "shredded cheese", "cheese"],
    "Shredded cheddar":        ["cheddar cheese", "cheddar", "shredded cheese", "mild cheddar", "cheese"],
    "Parmesan cheese":         ["parmigiano reggiano", "parmesan", "grated parmesan", "italian cheese", "cheese"],
    "Monterey jack cheese":    ["monterey jack", "jack cheese", "pepper jack", "shredded cheese", "cheese"],
    "Cottage cheese":          ["cottage cheese small curd", "small curd cottage", "low fat cottage", "cheese", "dairy"],
    "Half and half":           ["half half cream", "coffee cream", "light cream", "dairy creamer", "cream"],

    # ── Bread & Bakery ────────────────────────────────────────────────
    "White sandwich bread":    ["white sandwich bread", "white bread loaf", "sliced white bread", "sandwich white bread", "bread loaf"],
    "Whole wheat bread":       ["wheat bread loaf", "whole wheat sandwich bread", "whole wheat sliced bread", "wheat sandwich bread", "wheat loaf"],
    "Flour tortillas large":   ["large tortillas", "tortillas", "burrito tortillas", "wrap tortillas", "flatbread"],
    "Corn tortillas":          ["corn taco shells", "small tortillas", "tortillas", "taco shells", "tortilla"],
    "Hamburger buns":          ["burger buns", "sandwich rolls", "brioche buns", "kaiser rolls", "rolls"],

    # ── Grains & Pasta ────────────────────────────────────────────────
    "White rice long grain":   ["long grain rice", "white rice bag", "rice", "enriched rice", "carolina rice"],
    "Brown rice":              ["whole grain rice", "brown rice bag", "rice", "long grain brown", "grain"],
    "Jasmine rice":            ["jasmine rice bag", "thai jasmine rice", "fragrant rice", "long grain jasmine", "rice"],
    "Spaghetti pasta":         ["spaghetti noodles", "pasta", "thin spaghetti", "angel hair pasta", "barilla spaghetti"],
    "Penne pasta":             ["penne noodles", "pasta", "tube pasta", "rigatoni", "barilla pasta"],
    "Elbow macaroni":          ["macaroni", "pasta", "elbow pasta", "mac noodles", "small pasta"],
    "Egg noodles":             ["wide noodles", "pasta noodles", "broad noodles", "noodles", "pasta"],
    "Lasagna noodles":         ["lasagna sheets", "pasta sheets", "oven ready lasagna", "noodles", "pasta"],
    "Rolled oats":             ["oatmeal", "quaker oats", "oat flakes", "whole oats", "oats"],
    "Panko bread crumbs":      ["panko crumbs", "japanese breadcrumbs", "bread crumbs", "coating crumbs", "crumbs"],
    "Plain bread crumbs":      ["breadcrumbs", "italian bread crumbs", "seasoned bread crumbs", "coating", "crumbs"],
    "All purpose flour":       ["flour", "ap flour", "white flour", "enriched flour", "baking flour"],
    "Cornmeal":                ["corn meal", "yellow cornmeal", "polenta", "grits", "masa"],
    "Quinoa":                  ["quinoa grains", "white quinoa", "organic quinoa", "grain quinoa", "seeds"],
    "Ramen noodles":           ["ramen", "instant ramen", "noodle soup", "ramen soup", "instant noodles"],
    "Orzo pasta":              ["orzo", "rice shaped pasta", "small pasta", "risoni", "pasta"],

    # ── Canned & Jarred Goods ─────────────────────────────────────────
    "Canned diced tomatoes":             ["diced tomatoes can", "petite diced tomatoes", "tomato can", "canned tomatoes", "tomatoes"],
    "Canned crushed tomatoes":           ["crushed tomatoes can", "san marzano", "passata", "tomato puree", "tomatoes"],
    "Tomato paste":                      ["tomato paste can", "concentrated tomato", "double concentrate tomato", "tomato", "canned tomato"],
    "Tomato sauce":                      ["tomato sauce can", "marinara sauce", "pasta sauce", "tomatoes pureed", "canned sauce"],
    "Canned black beans":                ["black beans can", "whole black beans", "canned black beans", "black turtle beans", "dried black beans"],
    "Canned kidney beans":               ["kidney beans can", "red kidney beans", "beans", "canned beans", "dark red kidney"],
    "Canned chickpeas":                  ["garbanzo beans", "chickpea can", "canned garbanzo", "beans", "canned legumes"],
    "Canned corn":                       ["sweet corn can", "corn kernels", "whole kernel corn", "corn", "vegetable corn"],
    "Canned green beans":                ["green beans can", "cut green beans", "french style green beans", "beans", "vegetables"],
    "Canned coconut milk":               ["thai coconut milk", "coconut cream", "unsweetened coconut milk", "coconut", "dairy free milk"],
    "Canned chicken broth":              ["chicken stock", "chicken broth carton", "broth", "chicken soup base", "stock"],
    "Canned beef broth":                 ["beef stock", "beef broth carton", "broth", "beef soup base", "stock"],
    "Canned diced green chiles":         ["green chilies", "hatch green chiles", "mild green chiles", "chiles", "peppers canned"],
    "Refried beans":                     ["refried pinto beans", "beans refried", "canned refried", "bean dip", "beans"],
    "Canned pinto beans":                ["pinto beans can", "dried pinto beans", "beans", "canned beans", "pintos"],
    "Salsa jar":                         ["chunky salsa", "medium salsa", "tomato salsa", "fresh salsa", "salsa sauce"],
    "Marinara pasta sauce jar":          ["spaghetti sauce", "pasta sauce", "tomato sauce jar", "red sauce", "marinara jar"],
    "Diced tomatoes with green chiles":  ["tomatoes chiles", "tomatoes green chilies", "spicy diced tomatoes", "fire roasted tomatoes", "diced tomatoes"],
    "Canned lentils":                    ["lentils canned", "green lentils", "french lentils", "beluga lentils", "legumes"],
    "Artichoke hearts canned":           ["artichoke hearts jar", "artichoke", "marinated artichoke", "canned artichoke", "vegetables canned"],
    "Sun dried tomatoes jar":            ["sun-dried tomatoes", "dried tomatoes", "tomato packed in oil", "julienne tomatoes", "tomato"],
    "Roasted red peppers jar":           ["roasted peppers", "piquillo peppers", "sweet roasted peppers", "red peppers jar", "peppers"],
    "Canned pumpkin":                    ["pumpkin puree", "libby pumpkin", "pure pumpkin", "pumpkin can", "squash puree"],
    "Chicken noodle soup can":           ["chicken soup", "noodle soup", "campbell chicken", "soup can", "condensed soup"],
    "Tomato soup can":                   ["tomato bisque", "cream of tomato", "campbell tomato", "soup can", "condensed soup"],

    # ── Oils, Sauces & Condiments ─────────────────────────────────────
    "Olive oil":               ["extra virgin olive oil", "evoo", "light olive oil", "pure olive oil", "cooking oil"],
    "Vegetable oil":           ["canola oil", "vegetable cooking oil", "pure vegetable oil", "sunflower oil", "soybean oil"],
    "Sesame oil":              ["toasted sesame oil", "asian sesame oil", "dark sesame oil", "sesame", "oil"],
    "Soy sauce":               ["tamari", "low sodium soy", "sodium soy sauce", "liquid aminos", "coconut aminos"],
    "Worcestershire sauce":    ["worcestershire", "lea perrins", "steak sauce", "savory sauce", "condiment"],
    "Hot sauce":               ["tabasco", "louisiana hot sauce", "cayenne sauce", "pepper sauce", "chili sauce"],
    "Ketchup":                 ["tomato ketchup", "catsup", "heinz ketchup", "tomato sauce", "condiment"],
    "Yellow mustard":          ["mustard", "prepared mustard", "yellow mustard bottle", "french mustard", "mustard squeeze"],
    "Dijon mustard":           ["grey poupon", "stone ground mustard", "whole grain mustard", "mustard", "condiment"],
    "Mayonnaise":              ["mayo", "hellmann's mayo", "best foods mayo", "light mayo", "sandwich spread"],
    "Apple cider vinegar":     ["cider vinegar", "acv", "organic cider vinegar", "vinegar", "acid"],
    "White vinegar":           ["distilled vinegar", "clear vinegar", "white distilled", "vinegar", "acid"],
    "Balsamic vinegar":        ["balsamic glaze", "aged balsamic", "balsamic reduction", "vinegar", "italian vinegar"],
    "Honey":                   ["raw honey", "clover honey", "pure honey", "natural honey", "honey bear"],
    "Maple syrup":             ["pure maple syrup", "pancake syrup", "maple", "real maple", "syrup"],
    "Fish sauce":              ["thai fish sauce", "nam pla", "anchovy sauce", "red boat fish sauce", "asian sauce"],
    "Oyster sauce":            ["oyster flavored sauce", "asian oyster sauce", "stir fry sauce", "wok sauce", "asian sauce"],
    "Hoisin sauce":            ["lee kum kee hoisin", "chinese hoisin sauce", "asian hoisin sauce", "hoisin stir fry", "plum sauce"],
    "Sriracha":                ["rooster sauce", "chili garlic sauce", "asian hot sauce", "huy fong", "hot sauce"],
    "Ranch dressing":          ["hidden valley ranch", "buttermilk ranch", "ranch dip", "salad dressing", "dressing"],

    # ── Baking & Dry Goods ────────────────────────────────────────────
    "Granulated sugar":        ["white sugar", "cane sugar", "sugar bag", "pure cane sugar", "sweetener"],
    "Brown sugar":             ["light brown sugar", "dark brown sugar", "raw sugar", "sugar", "sweetener"],
    "Powdered sugar":          ["confectioners sugar", "icing sugar", "10x sugar", "sugar", "sweetener"],
    "Baking soda":             ["sodium bicarbonate", "arm hammer baking soda", "bicarbonate", "leavening", "baking"],
    "Baking powder":           ["double acting baking powder", "calumet baking powder", "leavening agent", "leavening", "baking"],
    "Salt":                    ["table salt", "sea salt", "kosher salt", "iodized salt", "sodium chloride"],
    "Black pepper":            ["ground pepper", "black peppercorns", "peppercorn", "pepper grinder", "spice pepper"],
    "Chicken bouillon cubes":  ["chicken bouillon", "bouillon cubes", "chicken base", "soup base", "chicken stock cube"],
    "Beef bouillon cubes":     ["beef bouillon", "bouillon cubes", "beef base", "soup base", "beef stock cube"],
    "Cornstarch":              ["corn starch", "baking cornstarch", "argo cornstarch", "cornstarch box", "starch"],
    "Vanilla extract":         ["pure vanilla", "vanilla flavoring", "vanilla bean extract", "imitation vanilla", "baking vanilla"],
    "Cocoa powder":            ["unsweetened cocoa", "dutch process cocoa", "dark cocoa", "cacao powder", "baking cocoa"],
    "Chocolate chips":         ["semi sweet chips", "baking chips", "chocolate morsels", "dark chocolate chips", "baking chocolate"],
    "Peanut butter":           ["creamy peanut butter", "jif peanut butter", "skippy", "natural peanut butter", "nut butter"],
    "Almond butter":           ["natural almond butter", "roasted almond butter", "nut butter", "almond spread", "peanut butter"],
    "Strawberry jam":          ["strawberry preserves", "strawberry jelly", "jam", "preserves", "fruit spread"],
    "Active dry yeast":        ["dry yeast", "instant yeast", "yeast packets", "fleischmann yeast", "baking yeast"],
    "Red lentils dried":       ["split red lentils", "dried lentils", "orange lentils", "red lentils", "legumes"],

    # ── Spices & Seasonings ───────────────────────────────────────────
    "Garlic powder":           ["granulated garlic", "garlic spice", "dried garlic", "garlic seasoning", "spice"],
    "Onion powder":            ["dried onion", "granulated onion", "onion spice", "onion seasoning", "spice"],
    "Cumin ground":            ["ground cumin", "cumin seeds", "cumin spice", "mexican spice", "spice"],
    "Chili powder":            ["chile powder", "chili seasoning", "chili spice", "ancho chili", "spice blend"],
    "Smoked paprika":          ["paprika smoked", "paprika", "sweet paprika", "hungarian paprika", "spice"],
    "Cayenne pepper":          ["cayenne", "ground cayenne", "red pepper powder", "hot pepper powder", "spice"],
    "Italian seasoning":       ["mccormick italian seasoning", "italian herb seasoning", "italian herb blend", "italian herbs spice", "mixed herbs"],
    "Oregano dried":           ["dried oregano", "ground oregano", "oregano leaves", "herb", "spice"],
    "Thyme dried":             ["dried thyme", "ground thyme", "thyme leaves", "thyme spice", "thyme seasoning"],
    "Rosemary dried":          ["dried rosemary", "ground rosemary", "rosemary herb", "herb", "spice"],
    "Bay leaves":              ["bay laurel", "dried bay leaves", "whole bay leaves", "bay leaf spice", "bay seasoning"],
    "Cinnamon ground":         ["ground cinnamon", "cinnamon powder", "cinnamon sticks", "cassia cinnamon", "spice"],
    "Curry powder":            ["curry seasoning", "yellow curry", "madras curry", "indian spice", "spice blend"],
    "Turmeric ground":         ["ground turmeric", "turmeric spice", "golden spice", "curcumin", "spice"],
    "Red pepper flakes":       ["crushed red pepper", "pepper flakes", "chili flakes", "crushed chili", "spice"],
    "Garam masala":            ["indian spice blend", "masala blend", "tikka masala spice", "curry spice", "spice blend"],
    "Taco seasoning":          ["taco mix", "mexican seasoning", "taco spice", "old el paso taco", "seasoning packet"],
    "Everything bagel seasoning": ["bagel seasoning blend", "everything spice", "sesame garlic blend", "everything seasoning", "seasoning mix"],
    "Old bay seasoning":       ["seafood seasoning", "old bay", "crab boil seasoning", "bay seasoning", "seafood spice"],
    "Coriander ground":        ["ground coriander", "coriander spice", "cilantro seed", "dried coriander", "spice"],
}


def get_search_term(ingredient_name: str) -> str:
    """Return the primary Kroger search term for a meal-cache ingredient name."""
    return KROGER_SEARCH_TERMS.get(ingredient_name, ingredient_name)


def get_fallback_terms(ingredient_name: str) -> list[str]:
    """Return the ordered list of 5 fallback search terms for an ingredient."""
    return KROGER_FALLBACKS.get(ingredient_name, [ingredient_name])


def get_all_terms(ingredient_name: str) -> list[str]:
    """Return primary term followed by all fallbacks — use to drive retry logic."""
    primary = get_search_term(ingredient_name)
    fallbacks = get_fallback_terms(ingredient_name)
    # Deduplicate while preserving order
    seen = set()
    result = []
    for t in [primary] + fallbacks:
        if t not in seen:
            seen.add(t)
            result.append(t)
    return result
